### ISSUE TITLE
Works locally, but not on GitHub pages

### ISSUE THREAD

**Issue by DaftLimmy-zz** [DaftLimmy/Swearing-Xylophone#1]
I gave GitHub pages a shot, but it didn't work: https://daftlimmy.github.io/Swearing-Xylophone/

Any idea what's wrong? It's all relative paths, I thought that would work.

**Comment by Harmelodic** [comment]
It doesn't seem to like createjs, If you see my Pull Request, I've cut out createJS and simplified the JavaScript down to the basics with the Audio API.
Example: https://harmelodic.github.io/Swearing-Xylophone/

**Comment by DaftLimmy-zz** [comment]
Thanks, I commented in your pull request.
